"""add new fiels to user model

Revision ID: 778504ff59d2
Revises: f862eba5eb72
Create Date: 2022-05-08 21:03:03.458556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778504ff59d2'
down_revision = 'f862eba5eb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
